title: Sparse - Model Optimization Testing
emoji: 🚀
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: 4.44.0
app_file: app.py
pinned: false
license: mit
suggested_hardware: cpu-basic
suggested_storage: small
